services:
  server:
    build: ./backend
    container_name: backendMysqlE
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: npm start dev

  db:
    image: mysql:8.0
    restart: always
    container_name: DBmysqlE
    env_file:
      - .env
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  frontend:
    build: ./frontend
    container_name: frontendMysqlE
    ports:
      - "3000:3000"
    depends_on:
      - server
    command: npm start

volumes:
  db_data:
